#!/usr/bin/env bash


#Iterate over the parameter to find all entered ones

for var in "$@"
do
	if [[ "$var" = '' ]]
	then
		shift
	fi
done

i=0;
for var in "$@"
do
	echo "$i. $var"	
	i=$((i+1))

done

